// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNLt0GEoCRT61lxewEuFA7V9ynJhY4zE',
    appId: '1:701818395387:web:d1ae118c580d0f005e2e5e',
    messagingSenderId: '701818395387',
    projectId: 'nikeapp-dee31',
    authDomain: 'nikeapp-dee31.firebaseapp.com',
    storageBucket: 'nikeapp-dee31.appspot.com',
    measurementId: 'G-EE2PDCC6YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtMyNnxQNQ0FjPAKWLRl1zRPRDK9Yl1g',
    appId: '1:701818395387:android:0ddaf4fc865488a85e2e5e',
    messagingSenderId: '701818395387',
    projectId: 'nikeapp-dee31',
    storageBucket: 'nikeapp-dee31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfIsMYc_F_yAceZw9qn8kCzUNT6bkafA',
    appId: '1:701818395387:ios:83242d6396b280c85e2e5e',
    messagingSenderId: '701818395387',
    projectId: 'nikeapp-dee31',
    storageBucket: 'nikeapp-dee31.appspot.com',
    iosClientId:
        '701818395387-sdc5l8ajlpsv7dfmsv4rq98bqll9cevm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nikeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfIsMYc_F_yAceZw9qn8kCzUNT6bkafA',
    appId: '1:701818395387:ios:83242d6396b280c85e2e5e',
    messagingSenderId: '701818395387',
    projectId: 'nikeapp-dee31',
    storageBucket: 'nikeapp-dee31.appspot.com',
    iosClientId:
        '701818395387-sdc5l8ajlpsv7dfmsv4rq98bqll9cevm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nikeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLNLt0GEoCRT61lxewEuFA7V9ynJhY4zE',
    appId: '1:701818395387:web:a0298e907d7465705e2e5e',
    messagingSenderId: '701818395387',
    projectId: 'nikeapp-dee31',
    authDomain: 'nikeapp-dee31.firebaseapp.com',
    storageBucket: 'nikeapp-dee31.appspot.com',
    measurementId: 'G-QJZV84H0QS',
  );
}
